services:
  - type: web
    name: vivino-bot
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: python bot.py
    healthCheckPath: /
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.4
      - key: PORT
        value: 10000